version: '3.9'
services:
  tyk-dashboard:
    image: tykio/tyk-dashboard:v4.3.3
    container_name: tyk-dashboard
    environment:
      - TYK_DB_LICENSEKEY=${TYK_DB_LICENSEKEY}
      - TYK_DB_STORAGE_MAIN_TYPE=mongo
      - TYK_DB_STORAGE_MAIN_CONNECTIONSTRING=mongodb://tyk-mongo:27017/tyk_analytics
    ports:
      - "3000:3000"
    env_file:
      - ./confs/tyk_analytics-lb.env
    networks:
      - tyk

  tyk-gateway1:
    image: tykio/tyk-gateway:v4.3.3
    # image: internal/tyk-gateway:std
    container_name: tyk-gateway1
    ports:
      - "8081:8080"
    env_file:
      - ./confs/tyk.env
    networks:
      - tyk

  tyk-gateway2:
    image: tykio/tyk-gateway:v4.3.3
    # image: internal/tyk-gateway:std
    container_name: tyk-gateway2
    ports:
      - "8082:8080"
    env_file:
      - ./confs/tyk-lb.env
    networks:
      - tyk

  tyk-pump:
    image: tykio/tyk-pump-docker-pub:v1.7.0
    container_name: tyk-pump
    env_file:
      - ./confs/pump.env
      - ./confs/pump.mongo.env
    networks:
      - tyk

  tyk-redis:
    image: redis
    container_name: tyk-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - tyk

  tyk-mongo:
    image: mongo:4.0
    container_name: tyk-mongo

    command: ["mongod", "--smallfiles"]
    ports:
      - "27017:27017"

    volumes:
      - db-data:/data/db

    networks:
      - tyk

  tyk-lb:
    image: nginx:1.21.6-alpine
    container_name: tyk-lb
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./confs/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./confs/www.tyk-test.com.crt:/etc/nginx/www.tyk-test.com.crt
      - ./confs/www.tyk-test.com.key:/etc/nginx/www.tyk-test.com.key
      - ./bundles:/usr/share/nginx/html/bundles
    networks:
      - tyk

volumes:
  redis-data:
  db-data:

networks:
  tyk: