version: '3.9'
services:
  tyk-dashboard:
    image: tykio/tyk-dashboard:${DASHBOARD_VERSION:-v5.6.1}
    container_name: tyk-dashboard
    environment:
      - TYK_DB_LICENSEKEY=${DASH_LICENSE:?License key missing from Docker environment file "".env" file.  Review The Getting Started steps in README.md.}
      - TYK_DB_STORAGE_MAIN_TYPE=mongo
      - TYK_DB_STORAGE_MAIN_CONNECTIONSTRING=mongodb://tyk-mongo:27017/tyk_analytics
    depends_on:
      tyk-mongo:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - ./confs/tyk_analytics.env
    networks:
      - tyk
  tyk-ent-portal:
    image: tykio/portal:${PORTAL_VERSION:-v1.11.0}
    command: --bootstrap
    ports:
      - 3001:3001
    environment:
      - PORTAL_LICENSEKEY=${DASH_LICENSE:?License key missing from Docker environment file "".env" file.  Review The Getting Started steps in README.md.}
    env_file:
      - ./confs/tyk_portal.env
    networks:
      - tyk

  tyk-gateway:
    image: tykio/tyk-gateway:${GATEWAY_VERSION:-v5.6.1}
    container_name: tyk-gateway
    ports:
      - "8080:8080"
    env_file:
      - ./confs/tyk.env
    networks:
      - tyk

  tyk-pump:
    image: tykio/tyk-pump-docker-pub:v1.11.0
    container_name: tyk-pump
    env_file:
      - ./confs/pump.env
      - ./confs/pump.mongo.env
    networks:
      - tyk

  tyk-redis:
    image: redis
    container_name: tyk-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - tyk

  tyk-mongo:
    image: mongo:4.0
    container_name: tyk-mongo
    command: ["mongod", "--smallfiles"]
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

    networks:
      - tyk

volumes:
  redis-data:
  db-data:

networks:
  tyk:
